### PR TITLE
Callbacks for finders, reload and flush

### PR DESCRIPTION
**Pull request by ghost**
Hi Ben,

We spoke about callbacks for finders, I have added the following functionality:
- Callbacks can now be given to all, count, create, each, find, first, last, pluck, reverse and uids. The 'load' method will be called in these circumstances to ensure data has been pulled using specified persistence.
- 'load' now performs a check to see if data has already been loaded before fetching it (by the use of a 'loaded' flag).
- Added a 'flush' method which clears the collection array and resets the loaded status.
- Added a 'reload' method for convenience which acts as a kind of "force load" as it flushes the collection and reloads the data from the specified persistence adapter.

All of the existing tests pass meaning the existing API is not broken by the changes. When going the callback/asynchronous route, usage-wise it's probably best to stick with callbacks for everything rather than mixing and matching. Further down the line, I would personally depreciate the non-callback approach and go completely asynchronous as you get a lot for free this way, never having to call 'load' (you will see a lot of "if (!callback)"'s currently to maintain existing API).

Hope you like the changes.

Cheers,

Jamie

### CODE REVIEW

**Comment by ghost** [comment]
Importantly, I forgot to mention that all new functionality is fully tested.

**Comment by grimen** [comment]
Does this mean say Post.all() will work as expected? I just tested master and the current implementation (not this patch included) don't really work as I expected. Peeped source and got a feeling master is work-in-progress still. Looking forward for full REST persistance, would be useful in my current project. :)

**Comment by ghost** [comment]
For Post.all() to work, you will first need to call 'load' which fetched data via REST. The changes in this fork however allow the following, without the need to call 'load':

```
Post.all(function(items) {
    // This function will be called when the request has completed successfully giving access to items.
});
```

Hope this helps.

**Comment by grimen** [comment]
Yes, thanks! The fork version of it looks like something I expected.

**Comment by benpickles** [comment]
What's the use-case for this, it seems to be that you want auto (just once) lazy loading?

@grimen was this the behaviour you were expecting from js-model, that `Post.all()` retrieves data from the server by default?

**Comment by ghost** [comment]
Hi Ben,

Think of it as a more asynchronous approach i.e. you don't have to check anything is loaded before calling 'all' and friends, as everything is lazy loaded and will automatically be available in the callback. I don't see any use-case (when working with persistence) that you wouldn't want the data to be available, so why not make it transparent.

A find just becomes:

```
Post.find(3, function(post) {
  // We know that post has been fetched for us either from localStorage or REST.
  $('#posts').append(post.attr('name'));
});
```

The 'all' method becomes:

```
Post.all(3, function(posts) {
  // We know that posts has been fetched for us either from localStorage or REST.
  console.log(posts);
});
```

Usage-wise, you now don't have to think about persistence, it is all handled by the persistence classes. The benefit of using callbacks is more apparent when using associations:

```
var Post = Model('post', { persistence: Model.LocalStoragePlusRest("/posts") }, {
  comments: function(callback) {
    var self = this;
    Comment.all(function(comments) {
      callback.call(self, Comment.chain(comments).select(function() {
        return this.attr('post_id') == self.id();
      }));
    });
  }  
});

Post.all(function(posts) {
  posts.each(function() {
    this.comments(function(comments) {
      // At this point, everything we need is loaded and it was loaded in the right 
      // order i.e. we needed the post's id before we could determine it's comments.
      console.log(comments.all());
    });
  });
});
```

The association stuff could be wrapped in a 'hasMany' macro-esque function like Rails (that is my next job) but you get the idea. From what I've seen of Node.js, it also makes heavy use of callbacks for similar reasons.

I hope this makes sense, as I said no existing functionality is changed, you just get a lot for free going the callback route. I managed to simplify the code no end on a project I'm working on just by going the callback route.

Cheers,

Jamie

**Comment by grimen** [comment]
@benpickles: My first assumption was - like Jamie seem to state as well - eager-loading, i.e. if there's no data loaded then if I call this method I most probably want this data if persistance is available.

@soniciq: Interesting to see your work and read your thoughts on this. 8) I'm very much agreeing on everything above.

**Comment by benpickles** [comment]
loading data with `load()` is already asynchronous and takes a callback -- you are also explicitly aware of when you're waiting on the server, which i think the app developer should be. whilst i don't disagree that a some methods could benefit from taking a callback i think it'd be limited to `find()` and perhaps `all()`.

this implementation is inconsistently applied -- you note that you should be aware that `detect()`, `select()`, `sort()` and `sortBy()` won't load data for you. it also assumes that you only retrieve data from your persistence layer once (the `loaded` flag) and you can only get everything all at once.

again, i'm not against some methods being more clever and knowing when to talk to the persistence layer but it should be more flexible and cater for more cases. for instance the following commit adds the capability of loading a specific model from your persistence layer which is more the direction that i think it should go:

http://github.com/tchak/js-model/commit/5b24881775b4d229a33f0bc5d6b41492bce4f040

**Comment by ghost** [comment]
Asynchronous was probably the wrong word, I actually meant that using callbacks ensures everything is loaded in the correct order, which in some cases needs to be asynchronous i.e. you cannot get all the comments for a given post if you do not yet have the post etc. The other key benefit is that your app only makes requests when it is necessary to do so, rather than loading all data all the time, saving potentially a great number of needless requests on an app with many models.

The exclusion of detect, select, sort and sortBy was deliberate as those methods already take a callback (see http://github.com/soniciq/js-model/blob/master/test/tests/model_class_methods.js#L51) and I thought it would be messy for them to take two functions as arguments. I am happy to add callbacks to these to make things consistent, or ideally come up with a cleaner solution.

To address the loaded flag, if you wanted to manually reload the data from persistence, there is now a 'reload' method for this purpose as well as a 'flush' method which essentially clears the loaded data.

That other commit is all well and good but having to think about when to load certain data should be (in my opinion) handled by the ORM/library. It's my idea of hell, having to have a series of load calls scattered amongst an otherwise clean API with conditions to determine which data needs loading... if this is the case I may as well do the json requests myself and add the objects manually.

I know when I first looked at js-model I was confused as to why a 'load' was needed and a believe @grimen had the same gripe. With and ORM such as this, you expect persistence to be handled for you, otherwise it's kind of like Rails expecting you to do a 'SELECT \* FROM posts' before you can call Post.find(). I'm of the opinion that the 'load' method could even be made private and it wouldn't be missed.

If you have time, I would encourage you to just try it on a small project as it has greatly cleaned things up for me and works more like you would expect an ORM to behave.

Cheers,

Jamie

p.s. The example I gave above could be rewritten to be even more concise using the 'each' class method as this will lazily load the data:

```
Post.each(function() {
  this.comments(function(comments) {
    // At this point, everything we need is loaded and it was loaded in the right 
    // order i.e. we needed the post's id before we could determine it's comments.
    console.log(comments.all());
  });
});
```

**Comment by ghost** [comment]
Hi Ben,

Congrats on the 0.9 release.

Have you had a chance to review these additions yet?

Cheers,

Jamie

**Comment by benpickles** [comment]
thanks, it was the biggest update yet :)

i haven't had a chance to play with this but i have been thinking about it!

i mentioned that it's inconsistent across all methods - but to make it consistent would also make it unfriendly. it's also simple to implement lazy loading yourself and in a way that solves it for your specific need - this implementation also only looks at one case: loading everything.

i won't be applying this patch for those reasons but i think that something along these lines could be really useful.

ben

**Comment by ghost** [comment]
That's disappointing as I've been using it and it fits nicely, reducing code complexity, hey ho.

You mentioned having callbacks in just 'find' and 'all', is it worth me implementing just this i.e. removing all the callbacks in the other methods? The only problem with 'all' is that there is no way to check if everything has already been loaded without the load/reload/flush functionality so it is likely that data could be mistakenly loaded multiple times.

I may create a fork of the project based on using callbacks and lazy loading. I've been looking into SproutCore and it's ORM is quite interesting, just a little too heavy-weight for my liking.

**Comment by benpickles** [comment]
sure, have a go. it's a difficult one because it'll involve defining a more detailed interface with persistence and making it relevent not only to REST. as you say it's also questionable whether `all()` should have this at all?

you woudn't need to fork necessarily, you could declare your custom methods in another file and overwrite the default `Model.ClassMethods` methods, they are then added to all your models at declaration time as per usual.

```
Model.ClassMethods.all = function(...) {
  ...
}

Model.ClassMethods.each = function(...) {
  ...
}
```

yeh SproutCore looks cool until you realise you have to write SproutCore instead of HTML, JavaScript and CSS... well that's how i remember it anyway.

**Pull request closed without merging**
